"""added new table archive

Revision ID: 2aec2a47cddf
Revises: 85dc92aebea0
Create Date: 2024-03-31 17:00:48.020217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aec2a47cddf'
down_revision = '85dc92aebea0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archive_fund', schema=None) as batch_op:
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('pending_fund', schema=None) as batch_op:
        batch_op.alter_column('comments',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_fund', schema=None) as batch_op:
        batch_op.alter_column('comments',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('archive_fund', schema=None) as batch_op:
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
