"""added new column coordinator_id

Revision ID: 51cee1688c60
Revises: 2aec2a47cddf
Create Date: 2024-04-04 05:21:22.648471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51cee1688c60'
down_revision = '2aec2a47cddf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archive_fund', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coordinator_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('fundraising', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coordinator_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('pending_fund', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coordinator_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_fund', schema=None) as batch_op:
        batch_op.drop_column('coordinator_id')

    with op.batch_alter_table('fundraising', schema=None) as batch_op:
        batch_op.drop_column('coordinator_id')

    with op.batch_alter_table('archive_fund', schema=None) as batch_op:
        batch_op.drop_column('coordinator_id')

    # ### end Alembic commands ###
