"""added new column coordinator_id

Revision ID: 64ecceb51d0e
Revises: 
Create Date: 2024-04-09 14:16:58.412577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64ecceb51d0e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archive', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coordinator_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coordinator_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('pending_project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coordinator_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coordinator_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coordinator_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_column('coordinator_id')

    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.drop_column('coordinator_id')

    with op.batch_alter_table('pending_project', schema=None) as batch_op:
        batch_op.drop_column('coordinator_id')

    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.drop_column('coordinator_id')

    with op.batch_alter_table('archive', schema=None) as batch_op:
        batch_op.drop_column('coordinator_id')

    # ### end Alembic commands ###
