"""budget_type column added

Revision ID: 7a904f4523c6
Revises: 64ecceb51d0e
Create Date: 2024-04-13 22:03:26.004987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a904f4523c6'
down_revision = '64ecceb51d0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archive', schema=None) as batch_op:
        batch_op.add_column(sa.Column('budget_type', sa.String(length=255), nullable=True))

    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.alter_column('budget_type',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('budget_cost', schema=None) as batch_op:
        batch_op.alter_column('budget_type',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.add_column(sa.Column('budget_type', sa.String(length=255), nullable=True))

    with op.batch_alter_table('current__budget', schema=None) as batch_op:
        batch_op.alter_column('budget_type',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('pending_project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('budget_type', sa.String(length=255), nullable=True))

    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('budget_type', sa.String(length=255), nullable=True))

    with op.batch_alter_table('total_budget', schema=None) as batch_op:
        batch_op.alter_column('budget_type',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('total_budget', schema=None) as batch_op:
        batch_op.alter_column('budget_type',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.drop_column('budget_type')

    with op.batch_alter_table('pending_project', schema=None) as batch_op:
        batch_op.drop_column('budget_type')

    with op.batch_alter_table('current__budget', schema=None) as batch_op:
        batch_op.alter_column('budget_type',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.drop_column('budget_type')

    with op.batch_alter_table('budget_cost', schema=None) as batch_op:
        batch_op.alter_column('budget_type',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.alter_column('budget_type',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('archive', schema=None) as batch_op:
        batch_op.drop_column('budget_type')

    # ### end Alembic commands ###
