"""fundraising table added

Revision ID: 85dc92aebea0
Revises: 
Create Date: 2024-03-31 14:14:54.139784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85dc92aebea0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('co_ammunity')
    with op.batch_alter_table('fundraising', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coordinator', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('project_name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('proposed_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('target_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('venue', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('event_organizer', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('lead_proponent', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('contact_details', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('donation_type', sa.String(length=255), nullable=False))
        batch_op.drop_column('subDepartment')
        batch_op.drop_column('budget')
        batch_op.drop_column('week')
        batch_op.drop_column('user')
        batch_op.drop_column('subprogram')
        batch_op.drop_column('end_date')
        batch_op.drop_column('totalWeek')
        batch_op.drop_column('cpf')
        batch_op.drop_column('community')
        batch_op.drop_column('start_date')
        batch_op.drop_column('cesap')
        batch_op.drop_column('cesap_filename')
        batch_op.drop_column('cna')
        batch_op.drop_column('department_A')
        batch_op.drop_column('cpf_filename')
        batch_op.drop_column('department')
        batch_op.drop_column('cna_filename')
        batch_op.drop_column('volunteer')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fundraising', schema=None) as batch_op:
        batch_op.add_column(sa.Column('volunteer', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('cna_filename', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('department', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('cpf_filename', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('department_A', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('cna', sa.BLOB(), nullable=True))
        batch_op.add_column(sa.Column('cesap_filename', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('cesap', sa.BLOB(), nullable=True))
        batch_op.add_column(sa.Column('start_date', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('community', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('cpf', sa.BLOB(), nullable=True))
        batch_op.add_column(sa.Column('totalWeek', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('end_date', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('subprogram', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('user', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('week', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('budget', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('subDepartment', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('donation_type')
        batch_op.drop_column('contact_details')
        batch_op.drop_column('lead_proponent')
        batch_op.drop_column('event_organizer')
        batch_op.drop_column('venue')
        batch_op.drop_column('target_date')
        batch_op.drop_column('proposed_date')
        batch_op.drop_column('project_name')
        batch_op.drop_column('coordinator')

    op.create_table('co_ammunity',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('community', sa.VARCHAR(length=255), nullable=False),
    sa.Column('program', sa.VARCHAR(length=255), nullable=False),
    sa.Column('subprogram', sa.VARCHAR(length=255), nullable=False),
    sa.Column('start_date', sa.DATE(), nullable=False),
    sa.Column('end_date', sa.DATE(), nullable=False),
    sa.Column('week', sa.INTEGER(), nullable=True),
    sa.Column('totalWeek', sa.INTEGER(), nullable=False),
    sa.Column('user', sa.VARCHAR(length=255), nullable=False),
    sa.Column('department', sa.VARCHAR(length=255), nullable=False),
    sa.Column('subDepartment', sa.VARCHAR(length=255), nullable=False),
    sa.Column('status', sa.VARCHAR(length=255), nullable=False),
    sa.Column('budget', sa.INTEGER(), nullable=False),
    sa.Column('cna', sa.BLOB(), nullable=True),
    sa.Column('cpf', sa.BLOB(), nullable=True),
    sa.Column('cesap', sa.BLOB(), nullable=True),
    sa.Column('cna_filename', sa.VARCHAR(length=255), nullable=True),
    sa.Column('cpf_filename', sa.VARCHAR(length=255), nullable=True),
    sa.Column('cesap_filename', sa.VARCHAR(length=255), nullable=True),
    sa.Column('department_A', sa.VARCHAR(length=255), nullable=True),
    sa.Column('volunteer', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
