"""added new column coordinator_id

Revision ID: b5c8a86cb71d
Revises: 51cee1688c60
Create Date: 2024-04-06 22:33:44.182369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5c8a86cb71d'
down_revision = '51cee1688c60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archive', schema=None) as batch_op:
        batch_op.alter_column('community',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('program',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('subprogram',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('totalWeek',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('department',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('subDepartment',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('budget',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('archive_fund', schema=None) as batch_op:
        batch_op.alter_column('program',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('coordinator',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('project_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('proposed_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('target_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('venue',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('event_organizer',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('lead_proponent',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('contact_details',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('donation_type',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.alter_column('community',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('program',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('subprogram',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('totalWeek',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('department',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('subDepartment',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('budget',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('fundraising', schema=None) as batch_op:
        batch_op.alter_column('program',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('coordinator',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('project_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('proposed_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('target_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('venue',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('event_organizer',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('lead_proponent',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('contact_details',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('donation_type',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.alter_column('userlog',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('action',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('pending_fund', schema=None) as batch_op:
        batch_op.alter_column('program',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('coordinator',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('project_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('proposed_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('target_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('venue',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('event_organizer',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('lead_proponent',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('contact_details',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('donation_type',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('pending_project', schema=None) as batch_op:
        batch_op.alter_column('community',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('program',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('subprogram',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('totalWeek',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('department',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('subDepartment',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('budget',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.alter_column('community',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('program',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('subprogram',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('totalWeek',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('department',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('subDepartment',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('budget',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.alter_column('program',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('subprogram', schema=None) as batch_op:
        batch_op.alter_column('program',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('subprogram',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
        batch_op.alter_column('program',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('program',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('subprogram', schema=None) as batch_op:
        batch_op.alter_column('subprogram',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('program',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.alter_column('program',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.alter_column('budget',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('subDepartment',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('department',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('user',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('totalWeek',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('subprogram',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('program',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('community',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('pending_project', schema=None) as batch_op:
        batch_op.alter_column('budget',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('subDepartment',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('department',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('user',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('totalWeek',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('subprogram',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('program',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('community',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('pending_fund', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('donation_type',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('contact_details',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('lead_proponent',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('event_organizer',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('venue',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('target_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('proposed_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('project_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('coordinator',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('program',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('action',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('userlog',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('fundraising', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('donation_type',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('contact_details',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('lead_proponent',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('event_organizer',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('venue',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('target_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('proposed_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('project_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('coordinator',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('program',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.alter_column('budget',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('subDepartment',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('department',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('user',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('totalWeek',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('subprogram',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('program',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('community',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('archive_fund', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('donation_type',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('contact_details',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('lead_proponent',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('event_organizer',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('venue',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('target_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('proposed_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('project_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('coordinator',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('program',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('archive', schema=None) as batch_op:
        batch_op.alter_column('budget',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('subDepartment',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('department',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('user',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('totalWeek',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('subprogram',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('program',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('community',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
