"""inkind new column donation quantity

Revision ID: eb18a0a6c1ab
Revises: 
Create Date: 2024-04-24 22:33:55.425229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb18a0a6c1ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donor_inkind', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))
        batch_op.alter_column('donation',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donor_inkind', schema=None) as batch_op:
        batch_op.alter_column('donation',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
